---
- name: Download Nagios Core source code
  get_url:
    url: "https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz"
    dest: "/tmp/nagios.tar.gz"

- name: Extract Nagios Core
  shell: "tar xzf /tmp/nagios.tar.gz -C /tmp"

- name: Compile and install Nagios Core
  shell: |
    cd /tmp/nagios-4.4.6 
    make all
    make install
    make install-init
    make install-config 
    make install-commandmode
  notify:
    - Restart Nagios

- name: Create Nagios web user
  user:
    name: nagiosadmin
    comment: Nagios Admin User
    groups: apache
  when: "ansible_facts['os_family'] == 'Debian'"

- name: Set Nagios web password
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: abgl061122
  when: "ansible_facts['os_family'] == 'Debian'"

- name: Configure firewall (CentOS)
  firewalld:
    service: http
    permanent: yes
    state: enabled
  when: "ansible_facts['os_family'] == 'RedHat'"

