---
- name: Enable and start Apache service
  service:
    name: apache2
    state: started
    enabled: yes
  when: "ansible_facts['os_family'] == 'Debian'"

- name: Enable and start Apache service (CentOS)
  service:
    name: httpd
    state: started
    enabled: yes
  when: "ansible_facts['os_family'] == 'RedHat'"

